"""initial_schema

Revision ID: 98bc7000904e
Revises: 
Create Date: 2026-05-27 13:26:17.936463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98bc7000904e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_reviews_tenant_created', 'access_reviews', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_access_reviews_id'), 'access_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_access_reviews_tenant_id'), 'access_reviews', ['tenant_id'], unique=False)
    op.create_table('controls',
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('company_control', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('evidence_required', sa.String(), nullable=True),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('control_id', 'tenant_id')
    )
    op.create_index('idx_controls_tenant_created', 'controls', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_controls_control_id'), 'controls', ['control_id'], unique=False)
    op.create_index(op.f('ix_controls_tenant_id'), 'controls', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('mttd_minutes', sa.Integer(), nullable=True),
    sa.Column('mttr_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index('idx_incidents_tenant_created', 'incidents', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('risks',
    sa.Column('risk_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('threat', sa.String(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('mitigation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('risk_id', 'tenant_id')
    )
    op.create_index('idx_risks_tenant_created', 'risks', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_risks_risk_id'), 'risks', ['risk_id'], unique=False)
    op.create_index(op.f('ix_risks_tenant_id'), 'risks', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('hashed_recovery_codes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_tenant_created', 'users', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendors_tenant_created', 'vendors', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('audit_findings',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_id', 'tenant_id'], ['controls.control_id', 'controls.tenant_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('finding_id', 'tenant_id')
    )
    op.create_index('idx_audit_findings_tenant_created', 'audit_findings', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_findings_finding_id'), 'audit_findings', ['finding_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_tenant_id'), 'audit_findings', ['tenant_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_id', 'tenant_id'], ['controls.control_id', 'controls.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('idx_evidence_tenant_uploaded', 'evidence', ['tenant_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('vendor_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('assessed_by', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('questionnaire_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendor_assessments_tenant_created', 'vendor_assessments', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vendor_assessments_id'), 'vendor_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_assessments_tenant_id'), 'vendor_assessments', ['tenant_id'], unique=False)
    op.create_table('capas',
    sa.Column('capa_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id', 'tenant_id'], ['audit_findings.finding_id', 'audit_findings.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capa_id', 'tenant_id')
    )
    op.create_index('idx_capas_tenant_created', 'capas', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_capas_capa_id'), 'capas', ['capa_id'], unique=False)
    op.create_index(op.f('ix_capas_tenant_id'), 'capas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capas_tenant_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_capa_id'), table_name='capas')
    op.drop_index('idx_capas_tenant_created', table_name='capas')
    op.drop_table('capas')
    op.drop_index(op.f('ix_vendor_assessments_tenant_id'), table_name='vendor_assessments')
    op.drop_index(op.f('ix_vendor_assessments_id'), table_name='vendor_assessments')
    op.drop_index('idx_vendor_assessments_tenant_created', table_name='vendor_assessments')
    op.drop_table('vendor_assessments')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index('idx_evidence_tenant_uploaded', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_findings_tenant_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_finding_id'), table_name='audit_findings')
    op.drop_index('idx_audit_findings_tenant_created', table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index('idx_vendors_tenant_created', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_tenant_created', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_risks_tenant_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_id'), table_name='risks')
    op.drop_index('idx_risks_tenant_created', table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index('idx_incidents_tenant_created', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_controls_tenant_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_control_id'), table_name='controls')
    op.drop_index('idx_controls_tenant_created', table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_access_reviews_tenant_id'), table_name='access_reviews')
    op.drop_index(op.f('ix_access_reviews_id'), table_name='access_reviews')
    op.drop_index('idx_access_reviews_tenant_created', table_name='access_reviews')
    op.drop_table('access_reviews')
    # ### end Alembic commands ###
