from pydantic import BaseModel, Field, ConfigDict, model_validator
from typing import Optional, List, Literal
from datetime import date, datetime
import html

class SanitizedBaseModel(BaseModel):
    @model_validator(mode="before")
    @classmethod
    def sanitize_strings(cls, data):
        if not isinstance(data, dict):
            return data
        
        excluded_keys = {
            "password", "code", "token", "temp_token", 
            "refresh_token", "redirect_uri", "mfa_secret"
        }
        
        def sanitize_val(key, val):
            if key in excluded_keys:
                return val
            if isinstance(val, str):
                return html.escape(val)
            if isinstance(val, dict):
                return {k: sanitize_val(k, v) for k, v in val.items()}
            if isinstance(val, list):
                return [sanitize_val(key, item) for item in val]
            return val

        return {k: sanitize_val(k, v) for k, v in data.items()}

class UserRegister(SanitizedBaseModel):
    """Schema for registering a new user within a tenant."""
    model_config = ConfigDict(extra="forbid")
    
    email: str = Field(..., description="The primary email address of the user, used as login identifier.")
    password: str = Field(..., min_length=8, description="The secure user password. Must be at least 8 characters long.")
    tenant_id: Optional[str] = Field(None, description="The unique identifier of the tenant organization. A new tenant ID is generated if not provided.")
    role: Optional[str] = Field("Viewer", description="The role of the user within the system. Allowed values: Viewer, GRC Analyst, Administrator.")

class UserLogin(SanitizedBaseModel):
    """Schema for authenticating a user to obtain access tokens."""
    model_config = ConfigDict(extra="forbid")
    
    email: str = Field(..., description="The registered email address of the user.")
    password: str = Field(..., description="The password for the user account.")

class MFAEnableRequest(SanitizedBaseModel):
    """Schema for requesting multi-factor authentication activation."""
    model_config = ConfigDict(extra="forbid")
    
    email: str = Field(..., description="The email address of the user enabling MFA.")
    code: str = Field(..., description="The valid TOTP code generated by the user's authenticator app.")

class MFALoginVerify(SanitizedBaseModel):
    """Schema for verifying a multi-factor authentication token during login."""
    model_config = ConfigDict(extra="forbid")
    
    temp_token: str = Field(..., description="The temporary JWT token issued after successful email/password validation.")
    code: str = Field(..., description="The 6-digit TOTP code from the authenticator app.")

class TokenResponse(BaseModel):
    """Response schema containing JWT access and refresh tokens along with user details."""
    model_config = ConfigDict(extra="forbid")
    access_token: str = Field(..., description="The cryptographic JWT access token used to authenticate requests.")
    refresh_token: str = Field(..., description="The secure token used to rotate expired access tokens.")
    token_type: str = Field("bearer", description="The token delivery scheme. Defaults to bearer.")
    role: str = Field(..., description="The authorized role of the authenticated user.")
    tenant_id: str = Field(..., description="The tenant organization associated with the authenticated user.")
    email: str = Field(..., description="The email address of the authenticated user.")

class PasswordResetRequest(SanitizedBaseModel):
    """Schema for requesting a password reset email."""
    model_config = ConfigDict(extra="forbid")
    
    email: str = Field(..., description="The email address requesting the password reset link.")
    redirect_uri: Optional[str] = Field(None, description="The allowed callback URL to redirect the user after password reset confirmation.")

class PasswordResetConfirm(SanitizedBaseModel):
    """Schema for confirming a password reset and establishing a new password."""
    model_config = ConfigDict(extra="forbid")
    
    token: str = Field(..., description="The cryptographically secure password reset token sent via email.")
    new_password: str = Field(..., min_length=8, description="The new secure password for the user account (minimum 8 characters).")

class UserResponse(BaseModel):
    """Response schema containing sanitized user profile information."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    
    id: int = Field(..., description="The unique auto-incrementing ID of the user record.")
    email: str = Field(..., description="The primary email address of the user.")
    role: str = Field(..., description="The active system role of the user (e.g. Viewer, GRC Analyst, Administrator).")
    tenant_id: str = Field(..., description="The tenant identifier scoping the user's workspace.")
    mfa_enabled: bool = Field(..., description="Indicates whether multi-factor authentication (MFA) is active for this account.")

class RegisterResponse(BaseModel):
    """Response schema for a newly registered user, including MFA provisioning keys."""
    model_config = ConfigDict(extra="forbid")
    message: str = Field(..., description="Status message indicating registration success.")
    email: str = Field(..., description="The registered email address.")
    tenant_id: str = Field(..., description="The assigned tenant ID.")
    role: str = Field(..., description="The assigned system role.")
    otp_secret: str = Field(..., description="The raw base32 secret key used to configure the MFA authenticator application.")
    otp_uri: str = Field(..., description="The otpauth:// URL string that can be encoded as a QR code for mobile scanner setup.")


# --- GRC Business Entity Schemas (Phase 05) ---

# Risk Schemas
class RiskCreate(SanitizedBaseModel):
    """Schema for recording a new risk item in the risk register."""
    model_config = ConfigDict(extra="forbid")
    risk_id: str = Field(..., description="A unique identifier for the risk (e.g., RISK-001).")
    asset: str = Field(..., description="The company asset or system affected by this risk.")
    threat: str = Field(..., description="The threat or vulnerability description (e.g., SQL Injection vulnerability).")
    likelihood: int = Field(..., ge=1, le=5, description="Likelihood score of the risk occurring (Scale: 1 to 5).")
    impact: int = Field(..., ge=1, le=5, description="Impact score if the risk occurs (Scale: 1 to 5).")
    mitigation: Optional[str] = Field(None, description="Detailed description of active or planned mitigations.")
    status: Optional[str] = Field("Open", description="The resolution status of the risk. Allowed values: Open, Mitigated, Closed.")
    owner: Optional[str] = Field(None, description="The designated owner responsible for monitoring this risk.")
    department: Optional[str] = Field(None, description="The company department associated with the risk scope.")
    review_date: Optional[date] = Field(None, description="The next scheduled review date for this risk.")

class RiskUpdate(SanitizedBaseModel):
    """Schema for updating details of an existing risk entry."""
    model_config = ConfigDict(extra="forbid")
    asset: Optional[str] = Field(None, description="The updated company asset or system name.")
    threat: Optional[str] = Field(None, description="The updated threat or vulnerability description.")
    likelihood: Optional[int] = Field(None, ge=1, le=5, description="Updated likelihood score (Scale: 1 to 5).")
    impact: Optional[int] = Field(None, ge=1, le=5, description="Updated impact score (Scale: 1 to 5).")
    mitigation: Optional[str] = Field(None, description="Updated mitigation description.")
    status: Optional[str] = Field(None, description="Updated resolution status (e.g., Open, Mitigated, Closed).")
    owner: Optional[str] = Field(None, description="Updated designated owner name/email.")
    department: Optional[str] = Field(None, description="Updated department name.")
    review_date: Optional[date] = Field(None, description="Updated review date.")

class RiskResponse(BaseModel):
    """Response schema containing full details of a logged risk, including calculated score and severity."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    risk_id: str = Field(..., description="The unique user-defined ID of the risk.")
    tenant_id: str = Field(..., description="The tenant ID scoping the risk ownership.")
    asset: str = Field(..., description="The affected system or corporate asset.")
    threat: str = Field(..., description="Description of the security threat.")
    likelihood: int = Field(..., description="Assessed likelihood score (1 to 5).")
    impact: int = Field(..., description="Assessed impact score (1 to 5).")
    risk_score: int = Field(..., description="The computed risk score (Likelihood * Impact). Scale: 1 to 25.")
    severity: str = Field(..., description="The qualitative risk severity classification (Critical, High, Medium, Low) based on risk score.")
    mitigation: Optional[str] = Field(None, description="The mitigation plan description.")
    status: str = Field(..., description="Current risk status.")
    owner: Optional[str] = Field(None, description="Current risk owner.")
    department: Optional[str] = Field(None, description="Current department.")
    review_date: Optional[date] = Field(None, description="Scheduled review date.")
    created_at: datetime = Field(..., description="Timestamp when the risk was registered.")
    updated_at: datetime = Field(..., description="Timestamp when the risk was last modified.")


# Control Schemas
class ControlCreate(SanitizedBaseModel):
    """Schema for defining a new security control mapping."""
    model_config = ConfigDict(extra="forbid")
    control_id: str = Field(..., description="The unique control identifier mapped to frameworks (e.g. AC-1, CC6.1).")
    framework: str = Field(..., description="The source regulatory framework or standard (e.g. SOC 2, ISO 27001, PCI-DSS).")
    description: str = Field(..., description="The precise requirement details of the control.")
    company_control: Optional[str] = Field(None, description="How the organization implements this control.")
    status: Optional[str] = Field("Not Started", description="Implementation status. Allowed values: Implemented, Partial, In Progress, Not Started.")
    owner: Optional[str] = Field(None, description="The security engineer or manager owning this control.")
    evidence_required: Optional[str] = Field(None, description="Description of evidence files needed to demonstrate compliance.")
    last_reviewed: Optional[date] = Field(None, description="Date when this control was last reviewed by compliance officers.")

class ControlUpdate(SanitizedBaseModel):
    """Schema for updating an existing security control mapping."""
    model_config = ConfigDict(extra="forbid")
    framework: Optional[str] = Field(None, description="Updated source regulatory framework.")
    description: Optional[str] = Field(None, description="Updated requirement details.")
    company_control: Optional[str] = Field(None, description="Updated organization implementation description.")
    status: Optional[str] = Field(None, description="Updated control status.")
    owner: Optional[str] = Field(None, description="Updated control owner.")
    evidence_required: Optional[str] = Field(None, description="Updated description of evidence requirements.")
    last_reviewed: Optional[date] = Field(None, description="Updated review date.")

class ControlResponse(BaseModel):
    """Response schema containing full security control mappings and status."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    control_id: str = Field(..., description="The unique control ID.")
    tenant_id: str = Field(..., description="The tenant ID scoping this control.")
    framework: str = Field(..., description="The source framework.")
    description: str = Field(..., description="The requirement details.")
    company_control: Optional[str] = Field(None, description="Internal implementation details.")
    status: str = Field(..., description="Current implementation status.")
    owner: Optional[str] = Field(None, description="Owner of the control.")
    evidence_required: Optional[str] = Field(None, description="Evidence requirements.")
    last_reviewed: Optional[date] = Field(None, description="Last review date.")
    created_at: datetime = Field(..., description="Timestamp when the control was created.")


# Incident Schemas
class IncidentCreate(SanitizedBaseModel):
    """Schema for registering a new security incident."""
    model_config = ConfigDict(extra="forbid")
    title: str = Field(..., min_length=1, description="A short descriptive title for the security incident.")
    severity: Literal["Critical", "High", "Medium", "Low"] = Field(..., description="Categorization of incident impact level.")
    status: Optional[Literal["Open", "Contained", "Resolved", "Closed"]] = Field("Open", description="The lifecycle status of the incident.")
    detected_at: Optional[datetime] = Field(None, description="Timestamp when the incident was first identified.")
    resolved_at: Optional[datetime] = Field(None, description="Timestamp when the incident was resolved.")
    description: Optional[str] = Field(None, description="Detailed narrative of the incident, impact, and response actions.")
    assigned_to: Optional[str] = Field(None, description="The incident response analyst assigned to this case.")

class IncidentUpdate(SanitizedBaseModel):
    """Schema for updating details of an active security incident."""
    model_config = ConfigDict(extra="forbid")
    title: Optional[str] = Field(None, description="Updated incident title.")
    severity: Optional[Literal["Critical", "High", "Medium", "Low"]] = Field(None, description="Updated incident severity.")
    status: Optional[Literal["Open", "Contained", "Resolved", "Closed"]] = Field(None, description="Updated status of the incident workflow.")
    detected_at: Optional[datetime] = Field(None, description="Updated detection timestamp.")
    resolved_at: Optional[datetime] = Field(None, description="Updated resolution timestamp. Triggers MTTR calculation.")
    description: Optional[str] = Field(None, description="Updated description details.")
    assigned_to: Optional[str] = Field(None, description="Updated assigned analyst email/name.")

class IncidentResponse(BaseModel):
    """Response schema containing incident details, response metrics (MTTD/MTTR)."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    incident_id: int = Field(..., description="The unique system-generated identifier for this incident.")
    tenant_id: str = Field(..., description="The tenant identifier scoping the incident.")
    title: str = Field(..., description="The incident title.")
    severity: str = Field(..., description="The current severity.")
    status: str = Field(..., description="The current workflow status.")
    detected_at: datetime = Field(..., description="The timestamp when detected.")
    resolved_at: Optional[datetime] = Field(None, description="The timestamp when resolved, if applicable.")
    mttd_minutes: Optional[int] = Field(None, description="Mean Time to Detect (in minutes), calculated as (detected_at - created_at) or similar.")
    mttr_minutes: Optional[int] = Field(None, description="Mean Time to Resolve (in minutes), calculated as (resolved_at - detected_at).")
    description: Optional[str] = Field(None, description="Detailed incident narrative.")
    assigned_to: Optional[str] = Field(None, description="Assigned responder.")
    created_at: datetime = Field(..., description="Timestamp when the incident log was initially created.")


# Vendor Schemas
class VendorCreate(SanitizedBaseModel):
    """Schema for onboarding a new third-party vendor."""
    model_config = ConfigDict(extra="forbid")
    name: str = Field(..., description="The legal name of the vendor organization.")
    status: Optional[str] = Field("Pending", description="Onboarding/assessment status (e.g. Active, Pending, Inactive).")
    score: Optional[int] = Field(None, description="The computed security assessment score (Scale: 0 to 100).")
    risk_tier: Optional[str] = Field(None, description="Calculated risk tier (Low, Medium, High, Critical) based on score.")
    contact_email: Optional[str] = Field(None, description="The primary security contact email at the vendor.")

class VendorUpdate(SanitizedBaseModel):
    """Schema for updating vendor record details."""
    model_config = ConfigDict(extra="forbid")
    name: Optional[str] = Field(None, description="Updated vendor name.")
    status: Optional[str] = Field(None, description="Updated vendor status.")
    score: Optional[int] = Field(None, description="Updated security score.")
    risk_tier: Optional[str] = Field(None, description="Updated risk tier.")
    contact_email: Optional[str] = Field(None, description="Updated vendor contact email.")

class VendorResponse(BaseModel):
    """Response schema containing full vendor details and calculated risk profiles."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    id: int = Field(..., description="The unique system ID of the vendor record.")
    tenant_id: str = Field(..., description="The tenant ID scoping the vendor relationship.")
    name: str = Field(..., description="The vendor name.")
    status: str = Field(..., description="Vendor status.")
    score: Optional[int] = Field(None, description="Security assessment score.")
    risk_tier: Optional[str] = Field(None, description="Determined risk tier classification.")
    contact_email: Optional[str] = Field(None, description="Vendor contact email.")
    created_at: datetime = Field(..., description="Timestamp when vendor profile was created.")
    updated_at: datetime = Field(..., description="Timestamp when vendor profile was last modified.")


# Vendor Assessment Schemas
class VendorAssessmentCreate(SanitizedBaseModel):
    """Schema for initiating a new security assessment questionnaire for a vendor."""
    model_config = ConfigDict(extra="forbid")
    vendor_id: int = Field(..., description="The ID of the vendor being assessed.")
    assessed_by: Optional[str] = Field(None, description="The analyst conducting the assessment.")
    assessment_date: Optional[datetime] = Field(None, description="The date when the assessment is scheduled or completed.")
    score: Optional[int] = Field(None, description="The raw numeric score computed from the questionnaire (0-100).")
    status: Optional[str] = Field("Draft", description="Current status of the questionnaire (e.g. Draft, Sent, Completed, Reviewed).")
    questionnaire_data: Optional[str] = Field(None, description="Serialized JSON string containing questions, sections, and answers.")

class VendorAssessmentUpdate(SanitizedBaseModel):
    """Schema for updating questionnaire answers or status in an assessment."""
    model_config = ConfigDict(extra="forbid")
    vendor_id: Optional[int] = Field(None, description="Updated vendor ID.")
    assessed_by: Optional[str] = Field(None, description="Updated assessor name/email.")
    assessment_date: Optional[datetime] = Field(None, description="Updated assessment date.")
    score: Optional[int] = Field(None, description="Updated assessment score.")
    status: Optional[str] = Field(None, description="Updated questionnaire status.")
    questionnaire_data: Optional[str] = Field(None, description="Updated questionnaire responses serialized JSON.")

class VendorAssessmentResponse(BaseModel):
    """Response schema containing assessment details and raw questionnaire data."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    id: int = Field(..., description="Unique assessment ID.")
    tenant_id: str = Field(..., description="The tenant ID scoping this assessment.")
    vendor_id: int = Field(..., description="The vendor ID under assessment.")
    assessed_by: Optional[str] = Field(None, description="The analyst who conducted the review.")
    assessment_date: Optional[datetime] = Field(None, description="Date of the assessment.")
    score: Optional[int] = Field(None, description="Determined numerical score.")
    status: str = Field(..., description="Current status.")
    questionnaire_data: Optional[str] = Field(None, description="JSON payload containing the detailed questionnaire sections and values.")
    created_at: datetime = Field(..., description="Timestamp when the assessment was created.")
    updated_at: datetime = Field(..., description="Timestamp when the assessment was last modified.")


# Audit Finding Schemas
class AuditFindingCreate(SanitizedBaseModel):
    """Schema for creating a new audit finding identified during reviews."""
    model_config = ConfigDict(extra="forbid")
    finding_id: str = Field(..., description="A unique identifier for the finding (e.g., FIND-2026-001).")
    title: str = Field(..., description="A summary of the compliance gap identified.")
    severity: str = Field(..., description="The severity of the gap (e.g., Critical, High, Medium, Low).")
    control_id: Optional[str] = Field(None, description="The mapped control ID that failed verification (if applicable).")
    recommendation: Optional[str] = Field(None, description="The recommended remediation actions to address the finding.")
    status: Optional[str] = Field("Open", description="The remediation status. Allowed values: Open, In Progress, Resolved, Closed.")

class AuditFindingUpdate(SanitizedBaseModel):
    """Schema for updating details or status of an existing audit finding."""
    model_config = ConfigDict(extra="forbid")
    title: Optional[str] = Field(None, description="Updated finding title.")
    severity: Optional[str] = Field(None, description="Updated finding severity.")
    control_id: Optional[str] = Field(None, description="Updated mapped control ID.")
    recommendation: Optional[str] = Field(None, description="Updated remediation recommendations.")
    status: Optional[str] = Field(None, description="Updated remediation status.")

class AuditFindingResponse(BaseModel):
    """Response schema representing an audit finding."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    finding_id: str = Field(..., description="Unique finding identifier.")
    tenant_id: str = Field(..., description="The tenant ID scoping this finding.")
    title: str = Field(..., description="The finding title.")
    severity: str = Field(..., description="The severity score.")
    control_id: Optional[str] = Field(None, description="The associated control ID.")
    recommendation: Optional[str] = Field(None, description="The recommendation description.")
    status: str = Field(..., description="Current remediation status.")
    detected_at: datetime = Field(..., description="Timestamp when the finding was detected.")
    created_at: datetime = Field(..., description="Timestamp when the finding record was created.")


# CAPA Schemas
class CapaCreate(SanitizedBaseModel):
    """Schema for creating a Corrective and Preventive Action (CAPA) plan."""
    model_config = ConfigDict(extra="forbid")
    capa_id: str = Field(..., description="A unique identifier for the CAPA action (e.g., CAPA-001).")
    finding_id: str = Field(..., description="The ID of the audit finding this CAPA aims to resolve.")
    title: str = Field(..., description="A short summary of the corrective/preventive action plan.")
    root_cause: Optional[str] = Field(None, description="Analysis of the root cause that led to the finding.")
    action: str = Field(..., description="Detailed description of the steps to execute.")
    owner: Optional[str] = Field(None, description="The designated person responsible for executing the CAPA.")
    due_date: Optional[date] = Field(None, description="The SLA deadline date for completing the actions.")
    status: Optional[str] = Field("Open", description="The action execution status. Allowed values: Open, In Progress, Completed, Closed.")

class CapaUpdate(SanitizedBaseModel):
    """Schema for updating a CAPA plan's progress or owner details."""
    model_config = ConfigDict(extra="forbid")
    finding_id: Optional[str] = Field(None, description="Updated associated finding ID.")
    title: Optional[str] = Field(None, description="Updated action plan title.")
    root_cause: Optional[str] = Field(None, description="Updated root cause analysis description.")
    action: Optional[str] = Field(None, description="Updated action details.")
    owner: Optional[str] = Field(None, description="Updated owner name/email.")
    due_date: Optional[date] = Field(None, description="Updated deadline date.")
    status: Optional[str] = Field(None, description="Updated status of the CAPA workflow.")

class CapaResponse(BaseModel):
    """Response schema containing details of a CAPA plan."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    capa_id: str = Field(..., description="Unique CAPA identifier.")
    tenant_id: str = Field(..., description="The tenant ID scoping this CAPA.")
    finding_id: str = Field(..., description="The associated finding ID.")
    title: str = Field(..., description="The action plan title.")
    root_cause: Optional[str] = Field(None, description="Detailed root cause analysis.")
    action: str = Field(..., description="Action steps detail.")
    owner: Optional[str] = Field(None, description="Assigned owner.")
    due_date: Optional[date] = Field(None, description="Target SLA deadline date.")
    status: str = Field(..., description="Current execution status.")
    created_at: datetime = Field(..., description="Timestamp when the CAPA was initialized.")


# Evidence Schemas
class EvidenceCreate(SanitizedBaseModel):
    """Schema for registering uploaded compliance evidence files."""
    model_config = ConfigDict(extra="forbid")
    evidence_id: str = Field(..., description="A unique identifier for the evidence entry.")
    control_id: str = Field(..., description="The security control ID supported by this evidence.")
    file_name: str = Field(..., description="The original name of the uploaded file.")
    file_path: str = Field(..., description="The storage path or URI where the evidence is located.")
    uploaded_by: str = Field(..., description="The email or name of the user who uploaded the file.")

class EvidenceResponse(BaseModel):
    """Response schema representing an evidence record."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    evidence_id: str = Field(..., description="Unique evidence ID.")
    tenant_id: str = Field(..., description="The tenant ID scoping this evidence.")
    control_id: str = Field(..., description="The associated control ID.")
    file_name: str = Field(..., description="Original filename.")
    file_path: str = Field(..., description="Stored file path.")
    uploaded_by: str = Field(..., description="Uploader email/name.")
    uploaded_at: datetime = Field(..., description="Timestamp when uploaded.")


# Access Review Schemas
class AccessReviewCreate(SanitizedBaseModel):
    """Schema for initiating a new user access review entry."""
    model_config = ConfigDict(extra="forbid")
    reviewer: str = Field(..., description="The administrator or manager conducting the access audit.")
    user_email: str = Field(..., description="The email address of the user whose access rights are being reviewed.")
    status: Optional[str] = Field("Open", description="Review status. Allowed values: Open, Completed.")
    decision: Optional[str] = Field(None, description="The certification decision. Allowed values: Approve, Revoke.")
    justification: Optional[str] = Field(None, description="Textual explanation and rationale for the decision.")

class AccessReviewUpdate(SanitizedBaseModel):
    """Schema for submitting decisions and justifications on access reviews."""
    model_config = ConfigDict(extra="forbid")
    reviewer: Optional[str] = Field(None, description="Updated reviewer email/name.")
    user_email: Optional[str] = Field(None, description="Updated target user email.")
    status: Optional[str] = Field(None, description="Updated review status.")
    decision: Optional[str] = Field(None, description="Updated decision (Approve or Revoke).")
    justification: Optional[str] = Field(None, description="Updated justification details.")

class AccessReviewResponse(BaseModel):
    """Response schema representing an access review record."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    id: int = Field(..., description="Unique record ID.")
    tenant_id: str = Field(..., description="The tenant ID scoping this review.")
    reviewer: str = Field(..., description="The reviewer ID/email.")
    user_email: str = Field(..., description="The email of the reviewed user.")
    status: str = Field(..., description="Review status.")
    decision: Optional[str] = Field(None, description="The final decision.")
    justification: Optional[str] = Field(None, description="The justification text.")
    reviewed_at: Optional[datetime] = Field(None, description="Timestamp when the review was submitted.")
    created_at: datetime = Field(..., description="Timestamp when the review record was created.")

class AuditLogResponse(BaseModel):
    """Response schema for structured JSON security audit logs."""
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    id: int = Field(..., description="Unique log ID.")
    tenant_id: str = Field(..., description="The tenant ID associated with the logged action.")
    user_email: str = Field(..., description="The email of the user who initiated the action.")
    action: str = Field(..., description="The action description (e.g. USER_LOGIN, RISK_CREATE).")
    ip_address: Optional[str] = Field(None, description="The client IP address from which the request originated.")
    timestamp: datetime = Field(..., description="The UTC timestamp of the activity.")
    details: Optional[str] = Field(None, description="Detailed JSON metadata detailing the scope and params of the action.")


# Dashboard Schema
class DashboardSummaryResponse(BaseModel):
    """Aggregated statistics returned to drive the central GRC metrics dashboard."""
    open_risks_count: int = Field(..., description="The count of risks in an Open state.")
    total_risks_count: int = Field(..., description="The total number of risks defined for the tenant.")
    avg_risk_score: float = Field(..., description="The mathematical average risk score across all risks.")
    risks_by_severity: dict = Field(..., description="Breakdown mapping severity levels (Critical, High, Medium, Low) to counts.")
    
    implemented_controls_count: int = Field(..., description="Count of security controls with 'Implemented' status.")
    total_controls_count: int = Field(..., description="Total count of security controls mapped for the tenant.")
    compliance_score: float = Field(..., description="Computed compliance percentage (Implemented / Total * 100).")
    controls_by_status: dict = Field(..., description="Breakdown of control counts by their implementation status.")
    controls_by_framework: dict = Field(..., description="Breakdown of control counts grouped by framework (e.g., SOC 2, ISO 27001).")
    
    open_incidents_count: int = Field(..., description="Count of active security incidents currently in 'Open' state.")
    active_incidents_count: int = Field(..., description="Count of incidents that are either 'Open' or 'Contained'.")
    total_incidents_count: int = Field(..., description="Total number of logged security incidents.")
    avg_mttd_minutes: float = Field(..., description="Average Mean Time to Detect (MTTD) in minutes.")
    avg_mttr_minutes: float = Field(..., description="Average Mean Time to Resolve (MTTR) in minutes.")
    incidents_by_severity: dict = Field(..., description="Count of incidents grouped by severity level.")
    incidents_by_status: dict = Field(..., description="Count of incidents grouped by response status.")
    
    open_findings_count: int = Field(..., description="Count of unresolved audit findings.")
    total_findings_count: int = Field(..., description="Total count of logged audit findings.")
    
    open_capas_count: int = Field(..., description="Count of open corrective action plans.")
    total_capas_count: int = Field(..., description="Total number of CAPA plans created.")


# Framework Schemas
class FrameworkSpecResponse(BaseModel):
    """Response schema describing a cataloged regulatory compliance framework."""
    model_config = ConfigDict(extra="forbid")
    id: str = Field(..., description="Unique shorthand ID for the framework (e.g., SOC2, ISO27001).")
    name: str = Field(..., description="The full regulatory name of the standard.")
    description: str = Field(..., description="Detailed description of the standard scope and goals.")
    version: str = Field(..., description="The specific release version of the standard (e.g. 2017, 2022).")
    category: str = Field(..., description="The category classification (e.g. Cybersecurity, Privacy, Financial).")
    total_controls: int = Field(..., description="Number of baseline security controls defined in this framework.")

